### ISSUE TITLE
Some questions about generating result html

### ISSUE THREAD

**Issue by githubcooperation** [yu02019/BEN#2]
I execute the following code
python BEN_infer.py -i E:\ProgramResearch\BEN\data\input -o E:\ProgramResearch\BEN\data\output -weight weight/Mouse_EPI_117T_2022_07191112/.hdf5
I meet this problem, can you give me some suggestions to solve this problem, thank you!
![image](https://user-images.githubusercontent.com/48356035/236590824-53d50f01-741f-4236-9502-9ddd67c12548.png)

**Comment by grandjeanlab** [comment]
got the same

when running BEN_infer, my masks are created seemingly alright, the report folder and images gets created, but not the html file. I get that error message. An error due to different pandas version?? I am on:
pandas 0.23.4

Traceback (most recent call last):
File "BEN/BEN_infer.py", line 49, in
make_logs_to_html(log_folder=logs_folder) # HTML logs will be saved in this folder
File "/project/4180000.41/ben/BEN/utils/check_html.py", line 69, in make_logs_to_html
pd.set_option('display.max_colwidth', None)
File "/home/traaffneu/joagra/.conda/envs/ben/lib/python3.6/site-packages/pandas/core/config.py", line 227, in call
return self.func(*args, **kwds)
File "/home/traaffneu/joagra/.conda/envs/ben/lib/python3.6/site-packages/pandas/core/config.py", line 123, in _set_option
o.validator(v)
File "/home/traaffneu/joagra/.conda/envs/ben/lib/python3.6/site-packages/pandas/core/config.py", line 764, in inner
raise ValueError(msg.format(typ=_type))
ValueError: Value must have type '<class 'int'>'
